"""İlk migration

Revision ID: 13d6a2d8b897
Revises: 
Create Date: 2025-03-07 19:39:49.008886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d6a2d8b897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('emergency_level', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kullanici_adi', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('sifre', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=255), nullable=False),
    sa.Column('soyad', sa.String(length=150), nullable=True),
    sa.Column('kimlik', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('treatment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bildirim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('baslik', sa.String(length=255), nullable=False),
    sa.Column('mesaj', sa.Text(), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('okundu', sa.Boolean(), nullable=True),
    sa.Column('arsivlendi', sa.Boolean(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hatirlatici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('kritik', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesaj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gonderen_id', sa.Integer(), nullable=False),
    sa.Column('alici_id', sa.Integer(), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('okundu', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alici_id'], ['kullanicilar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gonderen_id'], ['kullanicilar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_email', sa.String(length=100), nullable=False),
    sa.Column('baslik', sa.String(length=255), nullable=False),
    sa.Column('icerik', sa.Text(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_email'], ['kullanicilar.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saglik_verisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.Integer(), nullable=False),
    sa.Column('yas', sa.Integer(), nullable=False),
    sa.Column('cinsiyet', sa.String(length=10), nullable=False),
    sa.Column('tani', sa.String(length=100), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saglik_verisi')
    op.drop_table('notlar')
    op.drop_table('mesaj')
    op.drop_table('hatirlatici')
    op.drop_table('bildirim')
    op.drop_table('patients')
    op.drop_table('notifications')
    op.drop_table('kullanicilar')
    op.drop_table('emergency_calls')
    # ### end Alembic commands ###
