"""Hasta tablosuna kayit_tarihi eklendi

Revision ID: e94bb5f5eef2
Revises: 13d6a2d8b897
Create Date: 2025-03-12 13:49:27.950798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94bb5f5eef2'
down_revision = '13d6a2d8b897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanicilar', schema=None) as batch_op:
        batch_op.drop_column('soyad')
        batch_op.drop_column('kimlik')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kayit_tarihi', sa.DateTime(), nullable=True))
        batch_op.alter_column('diagnosis',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('diagnosis',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('kayit_tarihi')

    with op.batch_alter_table('kullanicilar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kimlik', sa.VARCHAR(length=11), nullable=True))
        batch_op.add_column(sa.Column('soyad', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
