"""Bildirim modeli eklendi

Revision ID: 99ba548be608
Revises: b13ed99b748d
Create Date: 2025-03-02 15:37:45.932947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ba548be608'
down_revision = 'b13ed99b748d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_calls')
    op.drop_table('patients')
    op.drop_table('notlar')
    op.drop_table('notifications')
    op.drop_table('health_data')
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sifre_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('sifre_hash')

    op.create_table('health_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=False),
    sa.Column('diagnosis', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notlar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kullanici_email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('baslik', sa.VARCHAR(length=255), nullable=False),
    sa.Column('icerik', sa.TEXT(), nullable=False),
    sa.Column('tarih', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_email'], ['kullanici.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=False),
    sa.Column('diagnosis', sa.VARCHAR(length=255), nullable=False),
    sa.Column('treatment_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('kayit_tarihi', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('emergency_level', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
